import { Product } from "./products.component";

export const ProductData: Array<Product> = [
  {id:1,name:"Product 1",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:2,name:"Product 2",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:3,name:"Product 3",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:4,name:"Product 4",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:5,name:"Product 5",description:"good product",imageUrl:"product-05.jpg",price:123},
  {id:6,name:"Product 6",description:"good product",imageUrl:"product-06.jpg",price:123},
  {id:7,name:"Product 7",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:8,name:"Product 8",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:9,name:"Product 9",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:10,name:"Product 10",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:11,name:"Product 11",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:12,name:"Product 12",description:"good product",imageUrl:"product-05.jpg",price:123},
  {id:13,name:"Product 13",description:"good product",imageUrl:"product-06.jpg",price:123},
  {id:14,name:"Product 14",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:15,name:"Product 15",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:16,name:"Product 16",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:17,name:"Product 17",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:18,name:"Product 18",description:"good product",imageUrl:"product-05.jpg",price:123},
  {id:19,name:"Product 19",description:"good product",imageUrl:"product-06.jpg",price:123},
  {id:20,name:"Product 20",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:21,name:"Product 21",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:22,name:"Product 22",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:23,name:"Product 23",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:24,name:"Product 24",description:"good product",imageUrl:"product-05.jpg",price:123},
  {id:25,name:"Product 25",description:"good product",imageUrl:"product-06.jpg",price:123},
  {id:26,name:"Product 26",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:27,name:"Product 27",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:28,name:"Product 28",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:29,name:"Product 29",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:30,name:"Product 30",description:"good product",imageUrl:"product-05.jpg",price:123},
  {id:31,name:"Product 31",description:"good product",imageUrl:"product-06.jpg",price:123},
  {id:32,name:"Product 32",description:"good product",imageUrl:"product-01.jpg",price:123},
  {id:33,name:"Product 33",description:"good product",imageUrl:"product-02.jpg",price:123},
  {id:34,name:"Product 34",description:"good product",imageUrl:"product-03.jpg",price:123},
  {id:35,name:"Product 35",description:"good product",imageUrl:"product-04.jpg",price:123},
  {id:36,name:"Product 36",description:"good product",imageUrl:"product-05.jpg",price:123},


]
